### ISSUE TITLE
This plugin is missing the required privacy provider

### ISSUE THREAD

**Issue by timhunt** [moodlehq/moodle-local_moodlemobileapp#51]
All plugin need to implement .../classes/privacy/provider.php - even if that is only a null provider.

If you install this plugin, and then do a full PHPunit run, the core test `provider_testcase::test_all_providers_compliant` fails with data set "local_moodlemobileapp".

**Comment by NoelDeMartin** [comment]
Thanks for letting us know, it's fixed now. Please, notice that this has been fixed in the `integration` branch, we recently switched to using the same branching strategy as the app repository (master -> stable branch, integration -> development branch).
