### ISSUE TITLE
There are only English language packs here. How can I get other language packs

### ISSUE THREAD

**Issue by msxmy** [moodlehq/moodle-local_moodlemobileapp#79]

**Comment by NoelDeMartin** [comment]
Hi there,

We track issues on `tracker.moodle.org`, so I'm closing this and feel free to follow up over there.

About this particular problem, you should be able to download other languages into your development machine running the `scripts/update_lang.sh` script. However, it may not work in your system if you don't have PHP or other dependencies installed. We already have an open issue to improve that: [MOBILE-3864](https://tracker.moodle.org/browse/MOBILE-3864)
